### PR TITLE
fixed bug in add-team-user command

### PR DESCRIPTION
**Pull request by a0viedo**
The response of the request was not parsed.

### CODE REVIEW

**Comment by SomeoneWeird** [comment]
Gah. Totally forgot about this. Thanks :tada:

**Comment by a0viedo** [comment]
@SomeoneWeird thank you!

**Comment by SomeoneWeird** [comment]
@mafintosh Does this need to be deployed?

**Comment by mafintosh** [comment]
@SomeoneWeird yea i'll do that - will try to setup a push hook from github sometime soon

**Comment by mafintosh** [comment]
Released in 1.3.1

**Comment by mafintosh** [comment]
... and deployed

**Pull request merged**
